spring:
  profiles:
    active: local # 어플리케이션이 실행될 때 default로 바라볼 것
    group:
      local:
        - common # local이 실행 될 때 common이 함께 실행 됨
      prod:
        - common # prod가 실행 될 때 common이 함께 실행 됨

--- # 파일로 나눈 것과 같은 효과
spring:
  config:
    activate:
      on-profile: common

  # 공통으로 설정할 값을 설정하며 개발
kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pharmacy-recommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create # deploy에서는 none, validate 중 하나를 사용해야 함. create는 테이블 drop 후 새로 생성하기 때문에 데이터 날아갈 수 있음
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: prod